name: OpenVPN Setup

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Pull OpenVPN Docker image
      run: docker pull openvpn/openvpn-as

    - name: Run OpenVPN container
      run: |
        docker run -d \
          --name=openvpn-as --cap-add=NET_ADMIN \
          -p 943:943 -p 443:443 -p 1194:1194/udp \
          -v /home/user/openvpn_data:/openvpn \
          openvpn/openvpn-as

    
    - name: Ip address 
      run: curl ifconfig.me
