name: Setup SSH Port Forwarding with Ngrok

on:
  push:
    branches:
      - main

jobs:
  setup-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: user list
        run: |
            node -v
            npm -v
